### PR TITLE
activate Travis-CI

### PR DESCRIPTION
**Pull request by mars3142**
Every new push to github will start a Travis CI job, if configured with your github account. You can see my builds at https://travis-ci.org/mars3142/clean-status-bar/builds

### CODE REVIEW

**Comment by abhijitnukalapati** [comment]
@mars3142 :+1:  

just curious - any reason why you didn't chose to use the `android` language for travis (helps with the verbosity of the travis file). perhaps, because it's in beta?

**Comment by emmaguy** [comment]
Only because I didn't know if existed! Very happy to improve and have a
shorter file, got a link to docs? Thanks!

**Comment by abhijitnukalapati** [comment]
@emmaguy the docs are [here](http://docs.travis-ci.com/user/languages/android/). To save time, I submitted a PR with the change - https://github.com/emmaguy/clean-status-bar/pull/55. I will leave it up to you to decide if it is really needed for the project

**Comment by emmaguy** [comment]
Thank you! I will take a look when I next have some time :)

**Pull request merged**
