### PR TITLE
it translation

### PR DESCRIPTION
**Pull request by DVDAndroid**

### CODE REVIEW

**Comment by emmaguy** [comment]
Awesome - thank you! Will merge and release when I next have some time :+1:

**Comment by DVDAndroid** [comment]
In my commit there is a string called "xposed_integration" because in my fork I created a new branch called xposed. I added a new feature: when an user open an app that call ```setStatusBarColor(int color)```, clean-status-bar tint it with same color

preview


do you like this feature? can i create a pull request?

**Comment by emmaguy** [comment]
Hmm - sorry, xposed is not really something I'm interested in. Thank you though

**Comment by DVDAndroid** [comment]
No problem.

**Pull request merged**
