### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by cypressious**
Kinda missed that you can update the travis config directly with the previous PR

### CODE REVIEW

**Comment by emmaguy** [comment]
No worries - it's useful have sdk manager anyway

**Comment by cypressious** [comment]
Agreed. I think that's all the PRs for today :) Any plans to release the BroadcastReceiver feature soon?

**Comment by emmaguy** [comment]
Yep - hopefully within the next 30 mins or so :smiley:

**Comment by cypressious** [comment]
Great!

**Pull request merged**
